# Generated by Django 2.2.5 on 2021-01-18 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('Product', models.CharField(blank=True, max_length=1000, null=True)),
                ('Created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建日期')),
                ('User', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
