# Generated by Django 2.2.5 on 2021-01-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Canceld',
            field=models.IntegerField(blank=True, max_length=1, null=True),
        ),
    ]
