# Generated by Django 2.2.5 on 2021-01-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_canceld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Canceld',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
